import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import { getCurrentSession } from "@/app/lib/auth/auth-utils";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`min-h-full bg-zinc-50 dark:bg-black text-zinc-900 dark:text-zinc-100 ${
          session ? "flex flex-col md:flex-row" : "flex flex-col"
        }`}
      >
        {session ? (
          <>
            <Sidebar />
            <div className="flex-1 min-w-0">
              {children}
            </div>
          </>
        ) : (
          <div className="flex-1 min-w-0 flex flex-col">
            <Navbar />
            <main className="flex-1">
              {children}
            </main>
          </div>
        )}
      </body>
    </html>
  );
}
