"""Make query_keyword_id optional in FetchHistory

Revision ID: 085c05736484
Revises: a1b2c3d4e5f6
Create Date: 2026-07-02 05:09:13.688244

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c05736484'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articleaction_article_id_fkey'), 'articleaction', type_='foreignkey')
    op.create_foreign_key(None, 'articleaction', 'newsarticle', ['article_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fetchhistory', 'query_keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fetchhistory', 'query_keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'articleaction', type_='foreignkey')
    op.create_foreign_key(op.f('articleaction_article_id_fkey'), 'articleaction', 'newsarticle', ['article_id'], ['id'])
    # ### end Alembic commands ###
