"""add_description_cloumn_query_keyboard_table

Revision ID: 1f3c6b6582ae
Revises: bd9ad74ad016
Create Date: 2026-06-30 10:12:16.498256

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3c6b6582ae'
down_revision: Union[str, Sequence[str], None] = 'bd9ad74ad016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('querykeyword', sa.Column('discription', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_querykeyword_keyword'), table_name='querykeyword')
    op.create_index(op.f('ix_querykeyword_keyword'), 'querykeyword', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_querykeyword_keyword'), table_name='querykeyword')
    op.create_index(op.f('ix_querykeyword_keyword'), 'querykeyword', ['keyword'], unique=True)
    op.drop_column('querykeyword', 'discription')
    # ### end Alembic commands ###
