"""Add fetch_history_id to NewsArticle

Revision ID: 689134add2f6
Revises: 79c7320ee471
Create Date: 2026-06-30 22:15:12.396230

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689134add2f6'
down_revision: Union[str, Sequence[str], None] = '79c7320ee471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsarticle', sa.Column('fetch_history_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'newsarticle', 'fetchhistory', ['fetch_history_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsarticle', type_='foreignkey')
    op.drop_column('newsarticle', 'fetch_history_id')
    # ### end Alembic commands ###
