"""Add detailed fetch stats and change to IST

Revision ID: 69afb365aff5
Revises: 689134add2f6
Create Date: 2026-07-01 19:12:23.573565

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69afb365aff5'
down_revision: Union[str, Sequence[str], None] = '689134add2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fetchhistory', sa.Column('total_fetched', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('fetchhistory', sa.Column('total_duplicates', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sourcefetchhistory', sa.Column('total_fetched', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('sourcefetchhistory', sa.Column('total_duplicates', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sourcefetchhistory', 'total_duplicates')
    op.drop_column('sourcefetchhistory', 'total_fetched')
    op.drop_column('fetchhistory', 'total_duplicates')
    op.drop_column('fetchhistory', 'total_fetched')
    # ### end Alembic commands ###
