"""add_query_keyword_table

Revision ID: bd9ad74ad016
Revises: 
Create Date: 2026-06-30 09:34:13.322784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9ad74ad016'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('querykeyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_querykeyword_keyword'), 'querykeyword', ['keyword'], unique=True)
    op.add_column('newsarticle', sa.Column('query_keyword_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'newsarticle', 'querykeyword', ['query_keyword_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsarticle', type_='foreignkey')
    op.drop_column('newsarticle', 'query_keyword_id')
    op.drop_index(op.f('ix_querykeyword_keyword'), table_name='querykeyword')
    op.drop_table('querykeyword')
    # ### end Alembic commands ###
