"""Add is_pinned to NewsSource and QueryKeyword

Revision ID: d6013b5d44fb
Revises: 085c05736484
Create Date: 2026-07-02 05:28:20.237226

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6013b5d44fb'
down_revision: Union[str, Sequence[str], None] = '085c05736484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newssource', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('querykeyword', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('querykeyword', 'is_pinned')
    op.drop_column('newssource', 'is_pinned')
    # ### end Alembic commands ###
