"""Add FetchHistory

Revision ID: f13f977c1264
Revises: 1f3c6b6582ae
Create Date: 2026-06-30 10:42:23.364250

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13f977c1264'
down_revision: Union[str, Sequence[str], None] = '1f3c6b6582ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetchhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_keyword_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('total_saved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_keyword_id'], ['querykeyword.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fetchhistory')
    # ### end Alembic commands ###
