"""Add advanced_query and exclude_domains

Revision ID: fc1dc7670b3f
Revises: d6013b5d44fb
Create Date: 2026-07-02 06:06:44.142214

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1dc7670b3f'
down_revision: Union[str, Sequence[str], None] = 'd6013b5d44fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newssource', sa.Column('advanced_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('querykeyword', sa.Column('advanced_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('querykeyword', sa.Column('exclude_domains', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('querykeyword', 'exclude_domains')
    op.drop_column('querykeyword', 'advanced_query')
    op.drop_column('newssource', 'advanced_query')
    # ### end Alembic commands ###
